controllers:
    resource: ../src/Controller/
    type: attribute

doctors.index:
    path: /doctors
    controller: App\Controller\DoctorController::index
    methods: GET

doctors.store:
    path: /doctors
    controller: App\Controller\DoctorController::store
    methods: POST

doctors.show:
    path: /doctors/{id}
    controller: App\Controller\DoctorController::show
    methods: GET


specialties.index:
    path: /specialties
    controller: App\Controller\SpecialtyController::index
    methods: GET

specialties.store:
    path: /specialties
    controller: App\Controller\SpecialtyController::store
    methods: POST

specialties.show:
    path: /specialties/{id}
    controller: App\Controller\SpecialtyController::show
    methods: GET
